.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md, CODE_OF_CONDUCT.md, LICENSE
- Add LICENSE
- Add CODE_OF_CONDUCT
- Add GitHub templates
=> Add missing project files.

package.json
So we can publish it in our npm organization.
=> Scope package to Netlify's organization.

package.json, yarn.lock
**- Summary**
This library uses the serverless cli internally. This package is missing from package.json.
=> Add missing dependencies.

package.json, src/finders.js, yarn.lock
**- Summary**
I was wrong, we don't need that dependency.
=> Remove unused reference.

.gitignore, README.md, package.json, src/finders.js
Closes https://github.com/netlify/zip-it-and-ship-it/issues/7
=> Use debug instead of `console.log`ing

package.json, src/zip.js
Closes https://github.com/netlify/zip-it-and-ship-it/issues/6
=> Add a promise all parallel limiter

.prettierrc.json, index.js, package.json, src/finders.js, src/serve.js, src/zip.js
**- Summary**
adding standard project level prettier config so as to have clean diffs
i went with what we have in netlify-dev-plugin but up to you what options you want: https://prettier.io/docs/en/options.html
```
{
"semi": false,
"singleQuote": true,
"printWidth": 120
}
```
please feel free to edit as you see fit!
=> add prettier

package.json, src/serve.js
**- Summary**
add visual identifier for ZISI so we can tell where each comes from. also disambiguate
added chalk for console output
🐸
=> add chalk and newline on logs for visual order

.eslintrc.json, CONTRIBUTING.md, README.md, package.json
**- Summary**
Add docs and eslint.  Clarify API and add CONTRIBUTING docs to describe the bundling step and why there is a minimal CLI here.
Its docs so just read those.  I added an eslint step.  Travis should be running these.  I'll check that now.
- Add Contributing docs
- Test codebase with eslint.
=> Contributing

.gitignore, package-lock.json, package.json
This upgrades Babel dependencies.
=> Upgrades Babel dependencies

package-lock.json, package.json, src/finders.js
This upgrades the `read-pkg-up` dependency. It fixes the related breaking changes.
=> Upgrade `read-pkg-up` dependency

README.md
This fixes `README` badges:
- remove Travis
- add test coverage badge
=> Fixes `README` badges

package-lock.json
This upgrades some dependencies that were triggering warnings from `npm audit`.
=> Upgrade some dependencies related to npm audit problem

.github/workflows/workflow.yml
At the moment, we only test macOS in CI (GitHub actions). This adds Ubuntu.
If the CI tests pass, I will add Windows to this PR too.
=> Test Ubuntu in CI

src/dependencies.js
This adds some code comments and refactor a line of code to put it into its own function.
=> Add some code comments

package-lock.json, package.json
This upgrades several production dependencies.
=> Upgrade production dependencies

package-lock.json, package.json
This upgrades the `tmp-promise` dependency.
=> Upgrade `tmp-promise`

package-lock.json, package.json
This upgrades the Husky dependency.
=> Upgrade Husky

package-lock.json, package.json
=> Upgrade Babel

package-lock.json, package.json
This upgrades the `auto-changelog` dependency.
=> Upgrades `auto-changelog`

package-lock.json, package.json
This upgrades the `adm-zip` dev dependency.
=> Upgrade `adm-zip`

renovate.json
=> Add `renovate.json`

.github/workflows/workflow.yml
This runs CI on Node 14 instead of Node 13.
=> Run CI on Node 14

.github/workflows/fossa.yml
**- Summary**
- adds back config to make fossa run correctly
- test it by running the github action in this branch
- fix fossa configuration
=> fix: fossa

.gitignore
=> Add `.vscode` to `.gitignore`

.github/workflows/release-please.yml, CONTRIBUTING.md, package-lock.json, package.json
Change release flow to use PRs
=> chore: add release PR flow

.eslintrc.js, src/main.js, src/runtime.js, tests/helpers/main.js, tests/main.js
This enables the `max-params` ESLint rule.
=> Enable `max-params` rule

.eslintrc.js, src/main.js
This enables the `complexity` ESLint rule
=> Enable the `complexity` ESLint rule

.eslintrc.js, src/resolve.js
This enables the `max-depth` ESLint rule.
=> Enable `max-depth` ESLint rule

.github/workflows/fossa.yml
**- Summary**
- fixes fossa error by removing github action lines that were erroring
- test in CI
- fix fossa configuration
=> fix: fossa error due to configuration errors

.github/workflows/labeler.yml
Add an action to label PRs based on title prefix
=> chore: add PR labeler

.github/workflows/workflow.yml, src/node_dependencies/resolve.js
=> ci: fix linting

src/main.js, src/node_dependencies/index.js
https://github.com/netlify/zip-it-and-ship-it/pull/330 exposed some errors added in https://github.com/netlify/zip-it-and-ship-it/pull/331
=> chore: fix lint errors

src/node_bundler/index.js
**- Summary**
This PR allows use esbuild to output any warnings or errors that arise from the bundling.
N/A
feat: use esbuild log output
=> feat: use esbuild log output

.github/workflows/workflow.yml
=> chore: run CI tests on latest Node 15.*

.github/PULL_REQUEST_TEMPLATE.md, .github/workflows/fossa.yml, .github/workflows/release-please.yml, .github/workflows/workflow.yml, README.md, codecov.yml, renovate.json5
=> chore: rename default branch from master to main

benchmarks/helpers/sample.js, benchmarks/index.js
**- Summary**
This PR adds a sample test to the benchmark suite. We'll use this to assess whether we can capture some of the variation in the benchmark results introduced by GitHub Actions.
N/A
chore: add sample test to benchmark
=> chore: add sample test to benchmark

.github/workflows/workflow.yml, package-lock.json, package.json, src/archive.js
**- Summary**
Upgrades `archiver` to version 5.x.
Closes #463.
N/A
🐷
=> fix: upgrade archiver to 5.x

.github/workflows/benchmark.yml, .github/workflows/release-please.yml
Follow up on https://github.com/netlify/zip-it-and-ship-it/pull/464
=> ci: use Node.js 16 in release please and benchmark

.github/workflows/pre-release.yml, CONTRIBUTING.md
Follow up on https://github.com/netlify/eslint-config-node/pull/244
Related to https://github.com/netlify/team-dev/issues/25
=> chore(ci): add prerelease action

src/runtimes/node/zip_esbuild.js, src/runtimes/node/zip_zisi.js, src/zip_node.js, tests/main.js
**- Summary**
Removes the feature flag and enables the behaviour, which has been fully rolled out in the Netlify platform, by default.
Adjusted tests.
=> feat: remove `experimentalHandlerV2` config property

.github/workflows/e2e-nextjs.yml, CHANGELOG.md
**- Summary**
Adjusting to https://github.com/netlify/netlify-plugin-nextjs/commit/e920cc674ce72fb232c513d8fddd42cb9f1d42f1.
=> chore: update Next.js E2E flow with monorepo support

src/runtimes/rust/builder.js, tests/main.js
**- Summary**
Installs the correct build target for Rust functions as part of the build command.
Existing tests updated.
🦀
=> fix: install Rust build target

.github/workflows/fossa.yml
Follow up on https://github.com/netlify/zip-it-and-ship-it/pull/621
=> chore: update fossa branch

.github/workflows/benchmark.yml, .github/workflows/e2e-nextjs.yml, .github/workflows/pre-release.yml, .github/workflows/release-please.yml, .github/workflows/workflow.yml
**- Summary**
Related with https://github.com/netlify/team-dev/issues/31 - cache `npm cache` between workflow executions.
=> chore(ci): cache npm cache dir between workflow execs

tests/helpers/test_many.js
**- Summary**
This PR adds a JSDoc comment to `makeTestMany` that gives better autocomplete to the testMany function.
- open in VS Code, try editing a variations array of `testMany`
=> chore: add autocomplete to testMany variations arg

tests/main.js
**- Summary**
Adds a new test to add more confidence to the change introduced by https://github.com/netlify/zip-it-and-ship-it/pull/788.
=> chore: add test

package.json
Follow-up to https://github.com/netlify/zip-it-and-ship-it/pull/698#pullrequestreview-800014246
=> Make sure that consumers use Precinct 8.2

tests/fixtures/node-force-builtin-v16/function.js, tests/main.js
this test was added as a very specific reproduction case, but since
was superceded by two more general tests.
Removed in a follow-up to https://github.com/netlify/zip-it-and-ship-it/pull/806.
**- Summary**
=> chore: remove unneeded v16 test

src/runtimes/node/parser/exports.ts, tests/fixtures/in-source-config/functions/cron_cjs_exports.js, tests/main.js
**- Summary**
This PR adds support for the `exports.handler` syntax to ISC.
reproduction test added.
=> feat: detect exports.handler in ISC

tests/helpers/main.js, tests/main.js
**- Summary**
Apparently there was a race condition where two unzippings running at the same time would haggle with each other. This PR fixes that race condition by unzipping synchronously. This unblocks #902.
test are green, even after multiple repetitions.
=> chore: fix flaky tests on windows

README.md, src/runtimes/node/bundlers/zisi/resolve.ts, src/runtimes/node/parser/index.ts
=> fix: fix a few typos

.gitignore, package-lock.json, package.json
**- Summary**
Less dependencies 🙂
- CI and Coverage is fine
=> chore: replace nyc with c8

tsconfig.json
**- Summary**
The supported Node.js version is >= 12 which means ES6 is outdated and produces more bloated code. You should make sure you use the same in all your projects :)
=> fix: use es2019 in tsconfig

package-lock.json, package.json, src/manifest.ts, src/runtimes/go/builder.ts, src/runtimes/node/finder.ts, src/runtimes/node/parser/index.ts, src/runtimes/node/utils/detect_es_module.ts, src/runtimes/node/utils/zip.ts, src/runtimes/rust/builder.ts, src/utils/archive_size.ts, src/utils/fs.ts, src/zip.ts, tests/main.js
=> fix: remove make-dir package and use `fs/promises`

package-lock.json, package.json
=> chore(deps): remove typescript from devDeps since it's a dependency

src/runtimes/go/index.ts, tests/main.js
This is a follow up to #955. When `zipGo` is enabled, we must zip the binary even if it was created from source by us, which is currently not handled.
=> feat: zip Go functions from source when `zipGo` is enabled

package.json
Part of https://github.com/netlify/zip-it-and-ship-it/issues/749
This adds support for ES modules-specific file extensions with our ESLint and Prettier setups.
---
🧑‍💻. This ensures we can discuss the changes and get feedback from everyone that should be involved. If you\`re
fixing a typo or something that\`s on fire 🔥 (e.g. incident related), you can skip this step.
=> chore: add support for `.cjs`, `.cts`, `.mjs` and `.mts`

.github/workflows/integration-tests.yml
This PR fixes our integration test, and makes sure that the Cypress suite of netlify-plugin-nextjs succeeds.
---
=> chore: try fixing integration test

package-lock.json, package.json, src/runtimes/node/bundlers/zisi/src_files.ts
This is a follow-up to #1069, where I commited a fix that's now [been merged](https://github.com/dependents/node-precinct/pull/108) into upstream precinct. This allows us to remove our fix in ZISI.
=> feat: update precinct

.github/codeql/codeql-config.yml, .github/workflows/codeql-analysis.yml
I would like to suggest a codeql scan workflow
Previously Implemented/Routine
---
=> chore: create codeql-analysis.yml

src/feature_flags.ts, src/runtimes/node/bundlers/esbuild/bundler.ts, src/runtimes/node/bundlers/nft/index.ts, tests/main.test.ts
Cleanup some FF which are at 100%
---
=> fix: cleanup resolved feature flags

README.md
Just a small docs addition
---
=> docs: add nft to nodeBundler in the docs

README.md
---
Fix some broken links in the readme.md file.
=> fix: fix broken links in readme.md

src/feature_flags.ts, src/runtimes/index.ts, src/runtimes/node/utils/entry_file.ts, src/runtimes/node/utils/zip.ts, tests/main.test.ts
=> fix: remove FF for new entry name

package-lock.json, package.json, src/runtimes/node/parser/exports.ts, src/runtimes/node/parser/index.ts
Follow-up to https://github.com/netlify/zip-it-and-ship-it/pull/1429 with changes requested by @danez.
=> fix: clean up V2 ISC implementation

tests/esbuild.test.ts, tests/main.test.ts, tests/zip_function.test.ts
=> chore: use const instead of hardcoded strings

src/runtimes/node/bundlers/esbuild/bundler_target.ts, src/runtimes/node/bundlers/index.ts, tests/fixtures/v2-api-ts/ts-function.ts, tests/v2api.test.ts
Fixes https://github.com/netlify/pod-dev-foundations/issues/534
This PR adds basic support for the V2 API and TypeScript, based on the draft that @danez outlined in the issue.
---
=> feat: support v2 API for TypeScript

src/main.ts, src/runtimes/node/in_source_config/index.ts, src/runtimes/node/index.ts, src/runtimes/runtime.ts, src/zip.ts, tests/unit/runtimes/node/in_source_config.test.ts, tests/v2api.test.ts, tests/zip_function.test.ts
Logs to systemLog if the feature flag is on and we find a v2 function.
=> feat: log to system-log if v2 function found

src/runtimes/node/utils/zip.ts
This is a follow-up to #1505 extending the logic for planting a `package.json` file with `{"type": "module"}` to the generation of a directory (as opposed to a ZIP file), which is used for local development in the CLI.
=> feat: extend `package.json` logic to `archiveFormat: "none"`

src/runtimes/node/in_source_config/index.ts, src/runtimes/node/parser/exports.ts, tests/unit/runtimes/node/in_source_config.test.ts
Part of https://github.com/netlify/pod-dev-foundations/issues/579.
Adds support for parsing the `method` ISC field to ZISI.
---
=> feat: parse `method` ISC field

src/runtimes/node/in_source_config/properties/schedule.ts
Fixes https://github.com/netlify/build/actions/runs/6481869897/job/17600853232?pr=5325#step:10:3157
Fixes an issue as babe/types is a cjs package and needs to be default imported
---
=> fix: @babel/types is a commonjs package and needs to be default imported

package-lock.json, package.json
fixes a issue where the package was not there upstream as it was a dev dependency
---
=> fix: make babel/types direct dependency

src/runtimes/node/utils/entry_file.ts, tests/fixtures-esm/v2-api-environment-variables/function.mjs, tests/v2api.test.ts
Fixes https://github.com/netlify/pod-dev-foundations/issues/602
Fixes an issue where `Netlify.env` was not available in the new V2 functions.
Tested with the CLI already and works
---
=> fix: make Netlify.env working by injecting it in the entry file

package-lock.json, package.json, src/runtimes/node/utils/included_files.ts, tests/fixtures-esm/symlinked-included-files/function.mjs, tests/fixtures-esm/symlinked-included-files/node_modules/crazy-dep, tests/main.test.ts, tests/symlinked_included_files.test.ts
Fixes https://linear.app/netlify/issue/COM-318/function-bundle-is-not-preserving-symlinks-therefore-duplicating-node
---
=> fix: preserve symlinks from included files in the resulting zip archive

src/feature_flags.ts, src/runtimes/node/bundlers/esbuild/src_files.ts, src/runtimes/node/bundlers/nft/index.ts, src/runtimes/node/bundlers/none/index.ts, src/runtimes/node/bundlers/zisi/src_files.ts, src/runtimes/node/utils/included_files.ts, tests/symlinked_included_files.test.ts
as suggested add the symlink fix behind a feature flag for #792 
---
=> chore: put the symlink fix behind a feature flag

src/main.ts
See https://github.com/netlify/cli/pull/6503#discussion_r1572029476
=> fix: export manifest types

package-lock.json, package.json, src/feature_flags.ts, src/runtimes/node/utils/entry_file.ts, src/runtimes/node/utils/zip.ts, tests/symlinked_included_files.test.ts, tests/telemetry.test.ts, tsconfig.json
Fixes https://linear.app/netlify/issue/COM-455/build-console-span-exporter-for-the-new-runtime
Once https://github.com/netlify/serverless-functions-api/pull/221 is released we need to update this PR with the version and then we can ship the newly added `___netlify-telemetry.mjs` file in each function bundle.
---
=> feat: ship instrumentation file in functions bundle
