src/serve.js

**- Summary**
using default port of 30001 makes it look like a string concat error. (users will see this: https://github.com/netlify/netlify-dev-plugin/issues/58) we use 34567 instead.
also when using default port, we should tell the user about it.

use assignLoudly to make clear defaultPort is not a mistake

---

src/zip.js

Before, mtime would affect the sha of the zips.  This sets it to date 0.

Fix sha stability for zip files

---

src/finders.js

Node-fetch is a very popular module, yet it uses undeclared peer dependencies.  This breaks some of our assumptions about whether or not we can safely skip peer and optional dependencies automatically.  If a module does something weird, it breaks that assumption (e.g. node-fetch not declaring peer deps).
Since this has been the number one complaint since we launched bundled deps, wee can add a single exception for this.

Don't fail when encoding is missing

---

package.json

**- Summary**
Most of our Ava configuration is not needed, as the values are the same as the default values with Ava.
Also the `concurrency` is set to `5` but this might be too much on some machines and too little on others (like mine). The default value (`os.cpus().length`) is more appropriate.
Simplify the Ava configuration.

Simplify Ava configuration

---

.eslintrc.json
bin.js
src/finders.js
src/zip.js
src/zip.test.js

**- Summary**
This ensures the `require()` statements are grouped: first the core modules, then the node modules, then the local imports. This is much easier to browse code when imports/require are on top of the file and grouped.
The `import/order` ESLint rule is added so that the grouping happens automatically on `eslint --fix`, i.e. we don't need to think about it. This happens on save if your IDE supports (VSCode does). 
Group `require()` statements together.

Group `require()` statements

---

.travis.yml
package.json

**- Summary**
Fixes #8.
This fixes CI setup:
- test on Node `8.5.0` and `12` instead of `10` and `12`, since our supported Node.js version is `8.5.0`.
- test on Ubuntu `18.04` instead of `14.04`.
- test on Windows and Mac OS as well, not only Linux.
- `sudo: false` in `.travis.yml` [is deprecated](https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration) and not used anymore.
- printing `node --version` and `npm --version` does not have to be explicit. It's already done by Travis CI.
- some syntax in `.travis.yml` could be simplified/removed thanks to default values (`npm i` and `npm test` are the default commands).
Also this adds test coverage with coveralls.
Fix CI setup.

Fix CI setup

---

package.json

**- Summary**
We don't have any `files` field in `package.json` nor `.npmignore`, so our npm package publishes every file.
```
$ npm pack --dry-run
npm notice 
npm notice 📦  @netlify/zip-it-and-ship-it@0.3.1
npm notice === Tarball Contents === 
npm notice 0     src/fixtures/no-package-json-example/node_modules/.keep                     
npm notice 0     src/fixtures/package-json-example/node_modules/.keep                        
npm notice 1.1kB LICENSE                                                                     
npm notice 72B   src/fixtures/go-simple/test.go~                                             
npm notice 188B  src/fixtures/no-package-json-example/functions/a-function/a-function.js     
npm notice 234B  src/fixtures/package-json-example/functions/a-function.js …
```

Add `files` field to `package.json`

---

.editorconfig

This fixes some cross-platform issues when developing on Windows by adding an [`.editorconfig` file](https://editorconfig.org).

Improve Windows development

---

package.json

This improves our Node.js support from `>= 8.12.0` to `>= 8.3.0`.
:tada:

Improve older Node.js support

---

.github/workflows/workflow.yml

This is a temporary fix to speed up GitHub actions for the moment.

Temporarily speed up GitHub actions

---

package.json

We don't need `dependency-check` since `eslint-plugin-node` already does this type of linting (and more).

Remove `dependency-check`

---

.gitignore
package.json

This speeds up ESLint by using caching.
This also print errors with the source code lines that failed.

Improve ESLint and Prettier configuration

---

.github/workflows/workflow.yml
README.md
package.json
scripts/coverage.sh

This uses Codecov for test coverage instead of Coveralls.
Coveralls has pending bugs with parallel test coverage which makes it not fit for multi-OS testing.

Use Codecov for test coverage

---

README.md

Hi there!
Tiny fix in the README for installing this package.
The install command should be `npm install @netlify/zip-it-and-ship-it` rather than `npm install zip-it-and-ship-it`.
Keep up the great work :heart:

README: Fix installation instructions

---

src/finders.js
src/fixtures/node-module-peer-optional/function.js
src/fixtures/node-module-peer-optional/package.json
src/main.test.js

- Summary
This updates the optional dependencies check to also check peer dependencies meta
The Peer Dependencies Meta field was added to Yarn here:
[Yarn#6671](https://github.com/yarnpkg/yarn/pull/6671)
This is used by a number of packages to allow them to be `yarn -pnp` compatible, most notably [Knex](https://github.com/knex/knex). 
This feature was added in version [0.20.1](https://github.com/knex/knex/blob/master/CHANGELOG.md#0201---29-october-2019)
- Test plan
Unit tests are included but cannot be run as it cannot get to that branch of the code in a similar way as the `Ignore missing optional dependencies` test.
- Description for the changelog
Check Peer Dependencies Meta for Optional Dependencies

Check peerDependenciesMeta for Optional Dependencies

---

README.md
src/bin.js
src/main.js
src/main.test.js

Go Functions can be bundled in two different modes:
1. Copied as is
2. Bundled in a `.zip` file
The `skipGo` option (called `zip-go` in the CLI with the inverse value) controls this.
We accidentally changed the default value of `skipGo` with the latest beta version of `zip-it-and-ship-it`. Go Functions are now bundled as `.zip` file (`2.`) instead of being copied as is (`1.`). Due to this, Go Functions are currently failing in production when Netlify Build beta is enabled (https://github.com/netlify/build/issues/1089). 
Part of the confusion was due to the fact that we are using:
- the `skipGo` boolean option programmatically
- the `--zip-go` boolean CLI flag, with an inverse value
This PR also introduces a `--skip-go` boolean CLI flag with the same value as the `skipGo` programmatic …

Fix Go Functions

---

README.md
src/bin.js
src/main.js
src/main.test.js

We currently have two options that do the same thing:
- `skipGo` is only in Node.js and defaults to `true`
- `zipGo` is only in the CLI and defaults to `false`. Its behavior is inverse to `skipGo`
To make it more consistent, #89 tried to enforce using `skipGo` only. However @mraerino pointed out that boolean option should ideally default to `false`. Therefore this PR switches to enforcing using `zipGo` only. `skipGo` is still kept for backward compatibility until the next major release.

Fix `skipGo` and `zipGo` options

---

.eslintrc.json
src/bin.test.js
src/dependencies.js
src/helpers/main.js
src/main.js
src/main.test.js
src/node.js

This PR makes `.eslintrc.json` consistent/identical with `@netlify/build`. There were some small differences.

Fix `.eslintrc.json`

---

CONTRIBUTING.md
package-lock.json
package.json

We used `pkg` to be able to run `zip-it-and-ship-it` in the buildbot without using Node.js directly. However with Netlify Build beta, `zip-it-and-ship-it` is now directly called by `@netlify/build` as a Node.js dependency.
I checked the other parts of our system that use `zip-it-and-ship-it` and they are all Node.js libraries that install it as a Node.js dependency. 
Maintaining `pkg` turns out to be quite involved (see #45). Therefore we can remove `pkg` from the publishing process.

Remove pkg

---

.github/workflows/workflow.yml
ava.config.js
package-lock.json
package.json
scripts/coverage.sh

This does some reorganizing of the development setup to mirror the latest changes in `netlify/build`:
- trigger GitHub actions on pull requests
- separate linting and testing GitHub actions
- do not pass Codecov token (since it's a public repository)
- use `verbose: true` configuration property with Ava
- re-order `package.json` properties
- add Husky hook to lint/prettify on `git push`
- re-organize and rename some npm scripts

Reorganize development setup

---

src/fixtures/node-module-typescript-types/function.js
src/main.test.js

This fixes some tests that were outdated. Files are now bundled under the `src/` directory and those tests were not updated.
Also the fixtures of two tests missed an empty directory due a missing `.gitkeep`.

Fix some tests

---

src/dependencies.js
src/main.test.js

Fixes #86.
This excludes TypeScript types from bundles since those are not needed in production code and only add to the size of the Function.

Do not bundle TypeScript types

---

src/dependencies.js

We renamed `prisma2` to `@prisma/cli`.

fix(dependencies): ignore `@prisma/cli`

---

src/dependencies.js
src/fixtures/side-module/function.js
src/fixtures/side-module/node_modules/.prisma/client/index.js
src/fixtures/side-module/node_modules/@prisma/client/index.js
src/fixtures/side-module/node_modules/@prisma/client/package.json
src/fixtures/side-module/package.json
src/main.test.js

Fixes #101.
Netlify Functions bundles their Node.js dependencies. By default, we bundle all published files of Node.js dependencies. However some Node.js modules (`@prisma/client`) generate source files on `postinstall` and put them in a parent directory (for example `node_modules/@prisma/client` creates `node_modules/.prisma/client`).
This PR adds support for this, with the specific `@prisma/client` use case.
This also adds tests for this.
@timsuchanek

Add support for dynamically generated source files

---

package-lock.json
package.json
src/dependencies.js
src/resolve.js

Fixes #104.
The `resolve` package uses a callback async signature. Due to [a bug in that package](https://github.com/browserify/resolve/issues/151#issuecomment-368210310), it does not work with `util.promisify`. Instead, `new Promise()` must be used.
This PR also upgrade `resolve` to the next major version, currently in beta, but that version probably solves more problems than it introduces.

Fix bug in `resolve()`

---

src/fixtures/symlinks/function/function.js
src/fixtures/symlinks/function/target.js
src/main.test.js
src/node.js
src/resolve.js

Fixes #106.
Symlinks in Functions do not always work due to two reasons:
- Zipping does not always keep them as symlinks. Instead we should archive the symlink target file, not the symlink itself.
- When there is no `package.json`, the absolute path is used to target files inside the zip archive. `resolve()` resolves symlinks with `realpath`, but this creates issues with absolute paths not having the same root directory.
This PR fixes those problems and adds a regression test.
This PR also fixes CI tests on macOS.

Fix using symlinks in Functions

---

package-lock.json
package.json
src/dependencies.js
src/resolve.js

Fixes #110 and #111.
The `resolve` library gives very unhelpful error messages. This means when we fail to find a plugin, the build error logs are confusing.
The `require.resolve()` can be used and does the same thing, but synchronously. This PR adds it as a fallback when `resolve` throws an error so that, in case of error, the message is clearer.
We cannot unfortunately use `require.resolve()` as the primary resolver because it does not preserve symlinks, which does not work with `zip-it-and-ship-it`. Also being synchronous is not great considering `zip-it-and-ship-it` is highly parallel.

Fix `resolve`

---

src/dependencies.js

This fixes a typo in a variable name.

Fix typo in variable name

---

src/dependencies.js
src/fixtures/invalid-require/function.js
src/main.test.js

Netlify Functions that do weird/invalid `require()` like `require('@scope')` currently fail with:
```
Cannot read property 'startsWith' of null 
```
[Bugsnag error](https://app.bugsnag.com/netlify/netlify-build/errors/5ed069ee275ecb0017438a5a).
This PR fixes this, and add a test for it.

Fix parsing invalid `require()`

---

src/node.js

This moves a line of code a little below.
Starting the Zip archive can be delayed a little down the code, as a performance optimization, in case they are errors while crawling for Node.js files.

Move a line of code

---

src/dependencies.js
src/node.js

We are looking for some directories roots by finding their `package.json`. This PR does a small optimization by delaying this call in order to run it in parallel.

Move another line of code

---

src/dependencies.js
src/fixtures/list/two/three.js
src/fixtures/list/two/two.js
src/main.js
src/main.test.js
src/node.js

`listFunctions()` returns the list of Netlify Functions main files.
However, in some cases, it is also useful to return the list of files required by those main files. For example, `netlify-plugin-inline-functions-env` [inlines those](https://github.com/bencao/netlify-plugin-inline-functions-env/pull/6) using environment variables.
This PR implements this, making `listFunctions()` return those as `srcFiles`.

Return list of files about to be bundled in `listFunctions()`

---

src/main.js
src/main.test.js

This PR splits `listFunctions()` into two methods:
- `listFunctions()`, which finds Functions main files
- `listFunctionsFiles()`, which also finds Functions required files, but is much slower
This allows `listFunctions()` to be much faster when required files are not needed.

Add `listFunctionsFiles()`

---

src/dependencies.js

Fixes #129.
It looks like like the `resolve` library sometimes resolves paths to `undefined` instead of `string`. This creates the following bug:
```
In file "/opt/build/repo/functions/test/test.js": The "path" argument must be of type string. Received undefined 
internal/validators.js:117:11 validateString
path.js:1128:5 dirname
node_modules/@netlify/zip-it-and-ship-it/src/dependencies.js:107:22 getModuleNameDependencies
node_modules/@netlify/zip-it-and-ship-it/src/dependencies.js:84:12 async getModuleDependencies
node_modules/@netlify/zip-it-and-ship-it/src/dependencies.js:47:21 async getFileDependencies
node_modules/@netlify/zip-it-and-ship-it/src/dependencies.js:19:12 async getDependencies
node_modules/@netlify/zip-it-and-ship-it/src/node.js:38:33 async filesForFunctionZip …
```

Fix `packagePath` being `undefined`

---

package-lock.json
package.json
src/dependencies.js
src/helpers/sha.js
src/main.test.js
src/node.js

The order in which files are added to a Zip archive does not change how they are extracted. However, this changes the archive's checksum.
Producing non-deterministic Zip archives prevents caching them based on their checksum. This is currently a problem in our API (https://github.com/netlify/ansible/issues/4282).
This PR ensures files are added in a deterministic order to the Zip archive by:
- Sorting them by file path
- Ensuring any parallelism does not make the archive non-deterministic
This also adds a regression test.

Ensure Zip archives contents are deterministic

---

scripts/coverage.sh

Codecov `-y` CLI flag was removed. `codecov.yml` is now automatically detected.

Fix Codecov

---

renovate.json5

`archiver` cannot be upgraded because v5 lacks support for Node 8.

Add `archiver` to skipped dependencies upgrades

---

renovate.json5

Adds a few more packages we can't update to a major version due to node 8 support:
```
locate-path
find-up
get-stream
```
Also, changes the logic to allow patch and minor versions

chore(deps): ignore major updates breaking node 8 support

---

renovate.json5

This adds `yargs` to the list of dependencies that do not support Node 8

Add `yargs` to `renovate.json5`

---

renovate.json5

Latest `del` does not support Node 8.

Add `del` to `renovate.json5`

---

renovate.json5

`pkg-dir@5` is not compatible with Node 8

Add `pkg-dir` to `renovate.json5`

---

README.md
src/dependencies.js
src/fixtures/list/four.js/four.js.js
src/main.js
src/main.test.js

Required by https://github.com/netlify/cli/issues/1477
Function names are important because they are the ones used in the function URL. 
They are different from the function filename since they do not include the file extension.
This PR returns the function `name` in both `listFunctions()` and `listFunctionsFiles()`.

Return function names in `listFunctions()` and `listFunctionsFiles()`

---

src/bin.test.js

When the root directory where this library is closed contains spaces in its file path, some tests are failing. This is especially common on Windows and was reported in https://github.com/sindresorhus/execa/issues/444.
This PR fixes this by switching from `execa.command()` to `execa()`.

Fix tests on Windows

---

src/dependencies.js

This slightly improves an error message.
`mainFile` is the absolute file path, which leads this error message to be too long unless a newline is used.

Improve error message

---

package-lock.json
package.json
src/archive.js
src/binary.js
src/dependencies.js
src/helpers/main.js
src/main.js
src/main.test.js
src/node.js

It's available since Node 8.0
**- Summary**
Reduce unneeded dependencies by relying on built-in functionality. `util.promisify` is a surprisingly heavy dependency since it relies on `es-abstract`.
Test suite still passes, no change of the interface.
Reduce dependencies by using native promisify function

Use native promisify instead of util.promisify

---

src/binary.js
src/main.js
src/main.test.js

This metadata file, called "netlify-toolchain" allows adding extra information about how the file was generated and what's in it without having to check other files.
This will help fixing https://github.com/netlify/build/issues/2114
Signed-off-by: David Calavera <david.calavera@gmail.com>

Add metadata file to binary zip files.

---

src/dependencies.js

This replaces arrays by sets in the Node.js dependencies logic.

Use `Set` in Node.js dependencies logic

---

.eslintrc.js
src/node.js
src/resolve.js

This enables the `no-shadow` ESLint rule.

Enable `no-shadow` ESLint rule

---

.eslintrc.js
src/resolve.js

This enables the `require-await` ESLint rule.

Enable `require-await` ESLint rule

---

.eslintrc.js
src/node.js

This enables the `node/prefer-global/buffer` ESLint rule.

Add `node/prefer-global/buffer` ESLint rule

---

.eslintrc.js
src/resolve.js

This enables the `promise/param-names` ESLint rule.

Enable `promise/param-names` ESLint rule

---

.eslintrc.js
src/dependencies.js

This enables the `fp/no-mutating-methods` ESLint rule.

Enable `fp/no-mutating-methods` ESLint rule

---

.eslintrc.js
src/archive.js
src/main.js
tests/main.js

This enables the `no-magic-numbers` ESLint rule.

Enable `no-magic-numbers` ESLint rule

---

.eslintrc.js
src/dependencies.js
tests/fixtures/invalid-require/function.js
tests/fixtures/many-dependencies/function.js
tests/fixtures/node-module-excluded/function.js
tests/fixtures/node-module-missing-conditional/function.js
tests/fixtures/node-module-missing-optional/function.js
tests/fixtures/node-module-peer-not-optional/function.js
tests/fixtures/node-module-peer-optional-none/function.js
tests/fixtures/node-module-peer-optional/function.js
tests/fixtures/node-module-typescript-types/function.js
tests/fixtures/side-module/function.js
tests/main.js

This enables some ESLint rules against dynamic `require()`.

Enable some ESLint rules against dynamic `require()`

---

renovate.json5

Latest major version of `precinct` requires Node.10

chore(deps): disable precinct major updates

---

package.json

Enforces syncing dependencies and passing tests before publishing a package.

chore: add prepublish script

---

src/node_dependencies/nested.js

**- Summary**
Prisma is going to rename the CLI package from `@prisma/cli` to `prisma`, so the excluded list needs to be updated with that new package name (and keep the older names for retro-compatibility).
add `prisma` CLI to EXCLUDED_PEER_DEPENDENCIES

fix: add `prisma` CLI to EXCLUDED_PEER_DEPENDENCIES

---

src/bin.js
src/info.js
src/main.js
src/runtimes/go.js
src/runtimes/index.js
src/runtimes/node.js
src/runtimes/rust.js
src/zip_node.js

**- Summary**
This PR includes [a bypass](https://github.com/netlify/zip-it-and-ship-it/blob/121bb49456a35ab99139160f3b99e12db1002d0f/src/main.js#L122-L124) for the legacy bundling logic when using esbuild, removing unnecessary computations and thus improving performance.
It also adds support for TypeScript.
Finally, to comply with the `max-lines` ESLint rule, it breaks the Go, JS and Rust runtime-specific logic into different files.
I'm sorry that the PR is larger than what I'd like, but the three changes are heavily interconnected.
feat: improvements to esbuild bundling

feat: improvements to esbuild bundling

---

src/node_dependencies/index.js
src/node_dependencies/special_cases.js
src/node_dependencies/traverse.js
src/runtimes/node.js
tests/main.js

**- Summary**
This PR adds special cases for the Next.js dependency quirks to the esbuild bundling mechanism.
It also handles the case where a module that isn't installed is included in `externalModules`. A corresponding test for this case is included.
Relevant tests were moved from being legacy-specific to the common test pool.
feat: add Next.js special case to esbuild bundler

feat: add Next.js special case to esbuild bundler

---

README.md
package-lock.json
package.json
src/bin.js
src/bundler.js
src/main.js
src/node_dependencies/index.js
src/node_dependencies/special_cases.js
src/node_dependencies/traverse.js
src/runtimes/go.js
src/runtimes/node.js
src/runtimes/rust.js
src/utils/consts.js
src/utils/remove_falsy.js
src/zip.js
src/zip_node.js
tests/fixtures/node-module-native/function.js
tests/fixtures/node-module-native/node_modules/test/index.js
tests/fixtures/node-module-native/node_modules/test/package.json
tests/fixtures/node-module-native/package.json
tests/helpers/main.js
tests/helpers/test_bundlers.js
tests/main.js

**- Summary**
This PR prepares zip-it-and-ship-it for the public rollout of esbuild. It includes the following breaking changes from the alpha:
1. A `jsBundler` parameter was introduced. Its possible values are:
- `zisi` (default): Bundle JS functions with the legacy mechanism
- `esbuild`: Bundle JS functions with esbuild
- `esbuild_zisi`: Bundle JS functions with esbuild and fallback to the legacy mechanism if it fails
2. The `useEsbuild` parameter was removed in favour of 1.
3. The `externalModules` parameter was renamed to `jsExternalModules`
4. The `ignoredModules` parameter was renamed to `jsIgnoredModules`
- Added a test for a module with native bindings
- Introduced a `testBundlers` helper function, which runs a test for each of the specified JS bundlers
**- …

feat: add JS bundler fallback

---

src/node_dependencies/index.js
tests/fixtures/dynamic-import/.eslintrc
tests/fixtures/dynamic-import/function.js
tests/main.js

When using an `import()` with a variable argument (as opposed to a string), `precint` returns `[undefined]` instead of `[]`. This leads the following function to fail:
https://github.com/netlify/zip-it-and-ship-it/blob/a437e74ea543b3cf2e51085ee9a3a86a9afba723/src/node_dependencies/index.js#L104-L106
This PR filters out `undefined`. This ensures bundling works. 
This only applies to the ZISI bundler. `esbuild` handles this case correctly.
This also adds tests for both ZISI and `esbuild` bundlers.

fix: fix and test dynamic import()

---

src/node_dependencies/special_cases.js
src/runtimes/node.js
tests/main.js

**- Summary**
This PR adds `@prisma/client` as a special case, treating it as an external module.
It also moves the evaluation of special cases a bit upstream, so that their external modules can be part of the traversal procedure.
N/A
fix: treat @prisma/client as an external module

fix: treat @prisma/client as an external module

---

src/node_bundler/index.js
tests/main.js

**- Summary**
This PR removes the esbuild plugin for handling `.node` files added in #353, because it doesn't cover all cases (e.g. where a library might require additional binary files) and actually prevents the ZISI fallback from kicking in.
Tests adjusted accordingly.
fix: remove esbuild plugin for detecting native bindings

fix: remove esbuild plugin

---

package-lock.json
package.json
renovate.json5

`semver@7` is incompatible with Node 8.
https://github.com/npm/node-semver/blob/093b40f8a7cb67946527b739fe8f8974c888e2a0/package.json#L36

chore: fix `semver` version with Node 8

---

README.md
src/bin.js
src/runtimes/go.js
src/zip.js
tests/main.js

Fixes #372.
The `skipGo`/`zipGo` parameter does not appear to be used by any user (including us), excepting for the CLI, which uses the default value.
https://github.com/netlify/cli/blob/3d8f1793ed90099152246fd4f69d44864762b55f/src/commands/functions/build.js#L56
We should remove those parameters. This would be a breaking change, i.e. require a major release.

chore!: remove `zipGo`/`skipGo` options

---

src/config.js
tests/main.js

**- Summary**
This PR changes the logic for computing the function configuration objects such that `undefined` values are ignored.
Added a new test.
fix: ignore undefined values when computing function config

fix: ignore undefined values when computing function config

---

src/zip.js
tests/main.js

**- Summary**
This PR adds the name of each bundled function to the output of `zipFunction` and `zipFunctions`, under the `name` property.
Closes #383.
Adjusted existing tests.
feat: add function name to output of zipFunction and zipFunctions

feat: add function name to output of zipFunction and zipFunctions

---

src/runtimes/node/bundler.js
tests/fixtures/node-typescript-with-imports/function.ts
tests/fixtures/node-typescript-with-imports/lib/util.ts
tests/main.js

**- Summary**
Adds `.ts` to the list of extensions that esbuild resolves automatically when resolving an import statement.
Fixes https://github.com/netlify/cli/issues/2183.
Added new test.
fix: add .ts to the list of esbuild resolved extensions

fix: add .ts to the list of esbuild resolved extensions

---

src/zip.js
tests/main.js

**- Summary**
Adds a `mainFile` property to the return value of the `zipFunction` and `zipFunctions` entrypoints. This makes it possible to unequivocally determine which bundles were generated from each input file, which is useful in CLI when serving bundled functions locally.
Adjusted existing tests.
feat: add `mainFile` to output of `zipFunction`/`zipFunctions`

feat: add `mainFile` to output of `zipFunction`/`zipFunctions`

---

src/runtimes/node/bundler.js

**- Summary**
Currently `sourceRoot` is set to an absolute path, which on Windows contains backslashes. However, this property is supposed to be a URL, so it needs to be converted to use forward-slashes. 
N/A

fix: use URLs in sourceRoot

---

.github/workflows/benchmark.yml
.github/workflows/release-please.yml
.github/workflows/workflow.yml

Part of https://github.com/netlify/team-dev/issues/19
This runs the CI on the `latest` Node.js version.

chore: run CI on `latest` Node.js

---

.github/workflows/workflow.yml
package-lock.json
package.json
renovate.json5
src/archive.js
tests/fixtures/node-module-optional-catch-binding/function.js

**- Summary**
Officially removes support for Node 8.
Closes #294.
N/A

feat: remove Node 8 support

---

renovate.json5

**- Summary**
Some packages can't be upgraded until we drop support for Node 10. This PR updates the Renovate config to that effect.
N/A
🐘

chore: add packageRules to Renovate config

---

src/main.js
src/runtimes/node/index.js
src/runtimes/node/src_files.js
tests/fixtures/list/five/index.ts
tests/fixtures/list/five/util.ts
tests/main.js

Ensures that `listFunctions()` and `listFunctionsFiles()` use the right default bundler based on the extension — e.g. TypeScript files will use esbuild even if not explicitly set in the config. This is in line with the `zipFunction()` and `zipFunctions()` methods.
Closes #512.

fix: add default bundler to listFunctions and listFunctionsFiles calls

---

package-lock.json
package.json
tests/fixtures/node-typescript-tsconfig-target/functions/function.ts
tests/fixtures/node-typescript-tsconfig-target/node_modules/module-name/index.js
tests/fixtures/node-typescript-tsconfig-target/node_modules/module-name/package.json
tests/fixtures/node-typescript-tsconfig-target/tsconfig.json
tests/main.js

**- Summary**
Upgrades esbuild to version 0.13.5 of the Netlify fork, which includes changes introduced in upstream version 0.12.8.
Includes an additional test to ensure that the compilation target that we define overrides any value set in a tsconfig.
👀 
🐽 
👄

feat: upgrade esbuild to @netlify/esbuild@0.13.5

---

src/node_dependencies/special_cases.js
tests/fixtures/node-module-excluded/function.js
tests/fixtures/node-module-excluded/node_modules/aws-sdk/index.js
tests/fixtures/node-module-excluded/node_modules/aws-sdk/package.json
tests/main.js

**- Summary**
The `aws-sdk` Node module is a special case. Because the module is injected automatically in the AWS Lambda environment, we want to leave any `require`/`import` calls untouched, but also we don't want to include its supporting files in the bundle.
This behaviour is being respected when using the ZISI bundler, but not with esbuild. We missed this even though we have a test specifically targeting this case, because the assertion was simply checking that `aws-sdk` was not part of the function's `node_modules`:
```js
t.false(await pathExists(`${tmpDir}/src/node_modules/aws-sdk`))
```
This is sufficient for ZISI, but not for esbuild, since the bundled modules will be inlined into the main file anyway.
This PR adds `aws-sdk` to the list of ignored modules and verifies that the …

fix: add aws-sdk to ignored_node_modules

---

src/runtimes/node/dynamic_imports/parser.js

**- Summary**
Adds some guards in the JS parsing section of the dynamic imports plugin.

fix: add guards in JS parsing

---

src/runtimes/node/dynamic_imports/parser.js
tests/fixtures/node-module-dynamic-import-template-literal/function.js
tests/fixtures/node-module-dynamic-import-template-literal/node_modules/@org/test/files/one.js
tests/fixtures/node-module-dynamic-import-template-literal/node_modules/@org/test/index.js
tests/fixtures/node-module-dynamic-import-template-literal/node_modules/@org/test/package.json
tests/fixtures/node-module-dynamic-import-template-literal/package.json
tests/fixtures/node-module-dynamic-import-unresolvable/function.js
tests/fixtures/node-module-dynamic-import-unresolvable/node_modules/@org/test/files/one.js
tests/fixtures/node-module-dynamic-import-unresolvable/node_modules/@org/test/index.js
tests/fixtures/node-module-dynamic-import-unresolvable/node_modules/@org/test/package.json
tests/fixtures/node-module-dynamic-import-unresolvable/package.json
tests/fixtures/node-module-dynamic-import/node_modules/@org/test/index.js
tests/fixtures/node-module-dynamic-import/node_modules/test-two/index.js
tests/main.js

**- Summary**
Adds support for more expression types when parsing dynamic import expressions.
Adjusted existing tests. Also added a new test which asserts that we leave alone any imports whose expressions we can't convert at build time.

feat: add more expressions to dynamic import parser

---

tests/main.js

**- Summary**
Adds a test asserting that negating files in the `included_files` will take precedence over any files included automatically in the bundle as part of processing a dynamic import.
For example, imagine the following import:
```js
const lang = require(`./lang-files/${myLang}.json`)
```
This would include all `.json` files inside `lang-files`. But if you happen to have files inside that directory that you don't want to include for some reason (e.g. maybe you know that `myLang` will never match them), you can exclude them from the bundle like so:
```toml
[functions]
included_files = ["!lang-files/not-a-lang.json", "!lang-files/*.not-a-lang.json"]
```

chore: add test

---

src/runtimes/node/bundler.js
src/runtimes/node/dynamic_imports/plugin.js
tests/main.js

**- Summary**
Puts processing of dynamic import expressions behind a `processDynamicNodeImports` configuration property, so that we can roll out the feature more gracefully.
Added new test and adjusted existing tests.

feat: add processDynamicNodeImports config property

---

.github/workflows/e2e-nextjs.yml

**- Summary**
The `NETLIFY_EXPERIMENTAL_FUNCTION_HANDLER_V2` environment variable has been decommissioned.

chore: remove CLI feature flag from Next.js E2E workflow

---

src/main.js
tests/main.js

**- Summary**
https://github.com/netlify/zip-it-and-ship-it/pull/537 added support for multiple source directories to the `zipFunction` and `zipFunctions` functions. This PR adds it to `listFunctions` and `listFunctionsFiles`.
Adds new tests.

feat: add support for multiple src directories to list methods

---

src/zip.js
tests/main.js

**- Summary**
The `basePath` parameter, which is required for dynamic import processing to work, is present in `zipFunctions` but missing in `zipFunction`. This PR fixes that.
New test added.
🐞

fix: add basePath parameter to zipFunction

---

src/runtimes/node/dynamic_imports/parser.js
src/runtimes/node/src_files.js
tests/fixtures/node-module-dynamic-import-4/function.js
tests/fixtures/node-module-dynamic-import-4/lang/en.js
tests/fixtures/node-module-dynamic-import-4/lang/nested/es.js
tests/fixtures/node-module-dynamic-import-4/lang/pt.js
tests/fixtures/node-module-dynamic-import-4/package.json
tests/main.js

**- Summary**
When processing dynamic import expressions, we create glob expressions by replacing variables with a wildcard character. For example:
- `./lang/${variable}.json` -> `./lang/*.json`
- `./scripts/${variable}` -> `./scripts/*`
By using `*` as the wildcard character, it means we'll only include the first level of files. So in the second example above, a file under a nested directory (e.g. `scripts/nested/foo.js`) would be left out.
This PR changes the wildcard character to `**` so that nested directories are also included.
Added new tests
🦁

feat: use double asterisk in dynamic import shim glob

---

README.md

**- Summary**
The `nodeSourcemap` configuration property was missing from the READMe. This PR fixes that.

chore: add nodeSourcemap config prop to README

---

README.md
src/bin.js
src/manifest.js
src/utils/fs.js
src/zip.js
tests/main.js

**- Summary**
Adds a new `manifest` property to `zipFunctions`. When set, it defines the path where a JSON-formatted file will be created, containing the list of all created functions as well as additional metadata properties.
This file can then be used by the CLI to know whether to reuse previously bundled functions as part of `build` and `deploy` commands.
New test added.

feat: add support for manifest file

---

src/manifest.js
tests/main.js

**- Summary**
Currently, the manifest file includes the entire output from `zipFunctions`, which can get quite large. The `inputs` property is particularly lengthy and is currently not required by the CLI when reading the manifest. This PR limits the manifest file to include only these properties:
- `mainFile`
- `name`
- `path`
- `runtime`
Existing test updated.

feat: simplify manifest format

---

src/runtimes/node/finder.js
src/runtimes/node/index.js
tests/fixtures/node-mjs/func1.mjs
tests/fixtures/node-mjs/func2/func2.mjs
tests/fixtures/node-mjs/func3/index.mjs
tests/main.js

**- Summary**
Adds support for JavaScript functions using a `.mjs` extension. These functions will use the esbuild bundler.
Closes #588.
New test added.

feat: allow JS functions with `.mjs` extension

---

package.json
renovate.json5

**- Summary**
Version 0.5.6 of `adm-zip` causes tests to fail (see https://github.com/netlify/zip-it-and-ship-it/pull/651/checks?check_run_id=3587767454). This locks the version to <=0.5.5.

chore: pin version of adm-zip

---

.github/workflows/e2e-nextjs.yml

**- Summary**
Similar to - https://github.com/netlify/cli/pull/3277 - for our e2e tests seems like we clone a total of 3 projects. We need to make use of the `cache-dependency-path`property to point to each of the lockfiles individually (see [here](https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#caching-packages-dependencies)).
- https://github.com/netlify/zip-it-and-ship-it/runs/3588927992?check_suite_focus=true

chore(ci): fix our npm caching strategy for our e2e nextjs tests

---

src/runtimes/node/list_imports.js
tests/fixtures/local-node-module-destructure-require/function.js
tests/fixtures/local-node-module-destructure-require/node_modules/@netlify/mock-package/index.js
tests/fixtures/local-node-module-destructure-require/node_modules/@netlify/mock-package/package.json
tests/fixtures/local-node-module-destructure-require/node_modules/@netlify/mock-package/stack.js
tests/fixtures/local-node-module-destructure-require/package.json
tests/fixtures/local-node-module-destructure-require/tsconfig.json
tests/main.js

**- Summary**
When parsing files with esbuild to find dependencies, we rely on the default `target` property set by esbuild, which is `esnext`. However, this is overridden by any `compilerOptions.target` property set in a `tsconfig.json`. When this value is set to `es5`, parsing with esbuild can fail because some expressions can't be lowered to ES5.
This PR explicitly sets `target: "esnext"` in esbuild so that no transpiling is required.
Added a new test.

fix: force esbuild target in zisi

---

renovate.json5

cc https://github.com/netlify/zip-it-and-ship-it/pull/694#issuecomment-933334715

chore: keep pkg-dir at v5 (closes #694)

---

.eslintrc.js
tests/main.js

**- Summary**
Removes some noise from the main tests file by moving some ESLint disable directives to the `.eslintrc.js` file.

chore: remove ESLint directives from tests file

---

.github/workflows/e2e-nextjs.yml

**- Summary**
Includes the build step introduced in https://github.com/netlify/zip-it-and-ship-it/pull/675 when running the Next.js E2E tests.

chore: run build step in Next e2e workflow

---

src/runtimes/node/bundlers/nft/index.ts
tests/main.js

**- Summary**
Temporarily reverts https://github.com/netlify/zip-it-and-ship-it/pull/759 and https://github.com/netlify/zip-it-and-ship-it/pull/783.

fix: disable ESM transpilation in NFT

---

src/feature_flags.ts
src/runtimes/node/bundlers/nft/es_modules.ts
src/runtimes/node/bundlers/nft/index.ts
src/runtimes/node/bundlers/nft/transpile.ts
tests/fixtures/local-require-esm/function_cjs/function_cjs.js
tests/helpers/main.js
tests/main.js

**- Summary**
Reinstates ESM transpilation when using NFT, which was temporarily disabled in https://github.com/netlify/zip-it-and-ship-it/pull/786. It's sitting behind a `nftTranspile` feature flag.
Unlike the initial implementation introduced by https://github.com/netlify/zip-it-and-ship-it/pull/759, this PR only transpiles a file to ESM (and patches any corresponding `package.json`) if all its parents are ESM files themselves, also candidates for transpilation.
Existing tests adjusted accordingly.

feat: reinstate ESM transpilation for NFT

---

package.json
tests/fixtures/node-force-builtin/function.js
tests/main.js

Adds a test asserting that we can handle imports with the `node:` prefix.

chore: add test for `node:` prefix

---

src/runtimes/node/utils/package_json.ts
tests/unit.js

**- Summary**
Some packages have a malformed `files` field. This PR adds sanitisation to catch that.
- added unit test

fix: sanitise package.json files field

---

src/runtimes/node/bundlers/esbuild/bundler.ts
src/runtimes/node/bundlers/esbuild/plugin_native_modules.ts
src/runtimes/node/bundlers/esbuild/plugin_node_builtin.ts
tests/fixtures/node-force-builtin-esm/function.js
tests/main.js

**- Summary**
fixes a bundling error that occurs when esbuild bundles a `node:`-namespaced  esm import.
cc https://github.com/nuxt/framework/issues/1826

fix: esm imports with node: prefix on esbuild

---

src/runtimes/node/utils/zip.ts
src/utils/fs.ts
tests/main.js

**- Summary**
When using `archiveFormat: "none"`, any files in `rewrites` are written to disk using `writeFile`. When doing this, we must ensure that the directory structure exists prior to the write operation. This PR addresses that.
Added a new test.

fix: ensure directories are created before writing files

---

package-lock.json
package.json
src/runtimes/node/bundlers/nft/transpile.ts
tests/fixtures/esm-throwing-error/.eslintrc
tests/fixtures/esm-throwing-error/function.js
tests/main.js

**- Summary**
When using NFT, generates a sourcemap for any transpiled files, whenever the `nodeSourcemap` property is set to `true`.
Added a new test.

feat: add sourcemap support to NFT

---

src/manifest.ts
src/utils/format_result.ts
tests/fixtures/with-schedule/func-1.js
tests/main.js

**- Summary**
Currently, any schedule data is surfaced in the result of `zipFunction` and `zipFunctions` as `config.schedule`. This PR adds a new top-level `schedule` property, which contains the same value.
This property will be useful when we introduce the in-code config declarations, because we'll be able to merge schedule data coming from the two types of sources and decide which one takes priority.
New test added.

feat: add new top-level `schedule` property

---

.github/workflows/workflow.yml
package-lock.json
package.json
src/main.ts
src/runtimes/node/bundlers/zisi/traverse.ts
src/utils/polyfills.ts

Fixes https://github.com/netlify/zip-it-and-ship-it/issues/748
This drops Node 10 support.
This does not drop Node 8/10 support as a compilation target (`nodeVersion` option) since I believe this is separate from the Node.js version supported for consumers installing this module through npm, but please let me know if this is incorrect.
This can be reviewed, but can only be released once https://github.com/netlify/build/pull/3873 is released.
I will also fix the branch protection rule right before merging this.

chore!: drop support for Node 10

---

renovate.json5

**- Summary**
Avoids things like https://github.com/netlify/zip-it-and-ship-it/pull/839.

chore: make Renovate ignore modules in fixtures

---

src/feature_flags.ts
src/runtimes/node/index.ts
tests/main.js

**- Summary**
Removes the `parseISC` feature flag, which has now been fully rolled out.
Existing test amended.

feat: remove `parseISC` feature flag

---

package-lock.json
package.json

Some builds are experiencing a big slowdown when we upgrade `@babel/parser` from `7.16.8` to `7.16.10` (note: there is no `7.16.9` release).
The only PR introduced by that release is https://github.com/babel/babel/pull/14130, so it appears to have some issues. It could be one of the following bugs, but we are not sure yet: https://github.com/babel/babel/issues/14182, https://github.com/babel/babel/issues/14175
We are certain that the problem comes from this specific package and this specific version. We also know the problem comes from `@babel/parser` as a direct dependency of `@netlify/zip-it-and-ship-it`, as opposed to as an indirect dependency through `precinct` and `node-source-walker`.
This PR pins the version of `@babel/parser` until we figure out why this version is creating a …

fix: pin `@babel/parser` to `7.16.8`

---

package-lock.json
package.json
renovate.json5

Reinstates https://github.com/netlify/zip-it-and-ship-it/pull/966, which was reverted by Renovate.
Also adds a rule to the Renovate config to prevent this from happening again.

chore: re-pin `@babel/parser` version

---

.eslintrc.js
package.json
src/config.ts
src/runtimes/node/index.ts
src/runtimes/node/utils/node_version.ts
tests/main.js
tests/unit/runtimes/node/utils/node_version.js
tests/unit/runtimes/node/utils/package_json.js

Also moves unit tests into separate files under a `test/unit` directory, matching the file structure of the files being unit-tested.

feat: adds `getNodeVersion` util

---

src/config.ts
src/feature_flags.ts
src/runtimes/node/bundlers/esbuild/bundler.ts
src/runtimes/node/bundlers/esbuild/index.ts
src/runtimes/node/bundlers/index.ts
src/runtimes/node/bundlers/nft/es_modules.ts
src/runtimes/node/bundlers/nft/index.ts
src/runtimes/node/bundlers/zisi/index.ts
src/runtimes/node/bundlers/zisi/list_imports.ts
src/runtimes/node/index.ts
src/runtimes/node/utils/entry_file.ts
src/runtimes/node/utils/module_format.ts
src/runtimes/node/utils/node_version.ts
src/runtimes/node/utils/normalize_path.ts
src/runtimes/node/utils/zip.ts
src/runtimes/runtime.ts
tests/fixtures/node-esm/func1.js
tests/fixtures/node-esm/func2/func2.js
tests/fixtures/node-esm/package.json
tests/main.js

As of last month, AWS Lambda [supports native ESM functions](https://aws.amazon.com/blogs/compute/using-node-js-es-modules-and-top-level-await-in-aws-lambda/). Currently, we're unable to take advantage of this functionality since zip-it-and-ship-it always generates CJS functions.
This PR starts changing that by generating pure ESM functions when all of the following conditions are met:
- The bundler is NFT
- The Node.js version (supplied via the `nodeVersion` configuration property) is greater than or equal to Node 14
- The `zisi_pure_esm` feature flag is enabled
In any other scenario, zip-it-and-ship-it continues to transpile ESM and generate CJS functions.

feat: generate pure ESM functions for NFT

---

src/runtimes/node/bundlers/nft/es_modules.ts

When using NFT, we determine whether an ESM file needs to be transpiled by checking whether all of its parents are also ESM files. We use the `reasons` object to figure out the parent/child relationships, but we need to account for the fact that the initial file is declared as a parent of itself.
This PR accounts for this case.

fix: guard against self-referencing element in `shouldTranspile`

---

benchmarks/esbuild.js
benchmarks/helpers/main.js
benchmarks/nft.js
benchmarks/package.json
benchmarks/zisi.js

Part of https://github.com/netlify/zip-it-and-ship-it/issues/749
Depends on #975
This migrates the benchmarks to using pure ES modules.
---
🧑‍💻. This ensures we can discuss the changes and get feedback from everyone that should be involved. If you\`re
fixing a typo or something that\`s on fire 🔥 (e.g. incident related), you can skip this step.

chore: use ES modules in benchmarks

---

src/runtimes/node/bundlers/esbuild/special_cases.ts
src/runtimes/node/bundlers/nft/es_modules.ts
src/runtimes/node/utils/package_json.ts

Use `getPackageJsonIfAvailable` instead of `getPackageJson`, to avoid throwing an error when transpiling ESM in NFT.

fix: use safe version of `getPackageJson` when transpiling ESM

---

.eslintrc.cjs
tests/helpers/main.js
tests/main.js

Part of https://github.com/netlify/zip-it-and-ship-it/issues/749
This replaces `require()` to dynamic `import()` in tests, as part of the migration to ES modules.
---
🧑‍💻. This ensures we can discuss the changes and get feedback from everyone that should be involved. If you\`re
fixing a typo or something that\`s on fire 🔥 (e.g. incident related), you can skip this step.

fix: use dynamic `import()` in tests

---

package.json

As discussed in https://github.com/netlify/zip-it-and-ship-it/pull/678#issuecomment-931400198, TypeScript is no longer needed as a prod dependency. This PR moves it to dev dependencies.

chore: move typescript to dev dependencies

---

package-lock.json

chore: move `typescript` to `devDependencies` in lock file

---

package-lock.json
package.json

At the moment, some users of `netlify-cli` will install an updated version of `@netlify/esbuild` that [fails some test](https://github.com/netlify/zip-it-and-ship-it/pull/1035). Let's pin down the version so people stay on the current one!

fix: pin down esbuild version

---

src/runtimes/node/bundlers/zisi/src_files.ts

Fixes tests on main. Read my PR to precinct upstream for more info: https://github.com/dependents/node-precinct/pull/108
Until precinct is fixed upstream, this PR fixes it on our end.
---

fix: adapt to new node:test module in node 18

---

.github/workflows/integration-tests.yml

When looking at https://github.com/netlify/zip-it-and-ship-it/pull/1080#issuecomment-1120830764, I was wondering "hm, does this mean I should take a look at this? 🤔". To make it obvious that this includes some e2e tests, I added the "cypress tests passed" line to the comment.

chore: add "cypress passed" comment to integration test

---

src/runtimes/node/bundlers/nft/es_modules.ts
src/runtimes/node/bundlers/nft/index.ts
src/runtimes/node/bundlers/nft/transpile.ts
tests/fixtures/node-esm-top-level-await-error/function.js
tests/main.js

Add customErrorInfo to errors happening during transpilation of esm with esbuild in the nft bundler.
I had to loop the function name through to the actual `esbuild` call, to generate the error location properly.
---

fix(nft): correctly annotate transpilation errors in nft bundler

---

src/runtimes/node/in_source_config/index.ts
src/runtimes/node/in_source_config/properties/schedule.ts
src/runtimes/node/parser/bindings.ts
src/runtimes/node/parser/exports.ts
tests/fixtures/in-source-config/functions/cron_esm_no_direct_export.js
tests/fixtures/in-source-config/functions/cron_esm_no_direct_export_renamed.js
tests/fixtures/in-source-config/functions/cron_esm_no_direct_export_renamed_reassigned.js
tests/fixtures/in-source-config/functions/cron_esm_schedule_reassigned.js
tests/main.js

scheduled functions which are reassigned or not directly exported are now detected
This PR extends the functionality of the detection for the in-source-config of scheduled functions.
2 cases were not supported previously:
1. The schedule is not directly supplied as string to the `schedule()` helper but assigned to a variable `schedule(SCHEDULE, ...)`
2. The schedule helper is not directly exported (`export const handler = schedule()`) but instead assigned to a variable which is exported `export { handler }`
To solve both of these cases I opted to collect all variable bindings and their current value (only in the root scope). This is done by iterating through all nodes and collecting all declarations of variables and all reassigns. This method is memoized so that multiple calls (at the …

fix: detect a wider range of scheduled functions

---

.eslintrc.cjs
src/archive.ts
src/bin.ts
src/main.ts
src/runtimes/go/builder.ts
src/runtimes/index.ts
src/runtimes/node/bundlers/esbuild/bundler.ts
src/runtimes/node/bundlers/zisi/list_imports.ts
src/runtimes/node/bundlers/zisi/published.ts
src/runtimes/node/bundlers/zisi/resolve.ts
src/runtimes/node/bundlers/zisi/side_files.ts
src/runtimes/node/bundlers/zisi/src_files.ts
src/runtimes/node/bundlers/zisi/traverse.ts
src/runtimes/node/in_source_config/properties/schedule.ts
src/runtimes/node/index.ts
src/runtimes/node/parser/bindings.ts
src/runtimes/node/parser/exports.ts
src/runtimes/node/utils/module.ts
src/runtimes/node/utils/normalize_path.ts
src/runtimes/node/utils/package_json.ts
src/utils/matching.ts
src/zip_binary.ts

As discussed in #1105, this new eslint rule enforces newlines before returns and after variable delcarations. I did not enable it for the tests, as that would change a lot.
Might be worth upstreaming this to the netlify eslint config?
The rule is already upstream but has no config https://github.com/netlify/eslint-config-node/blob/main/.eslintrc.cjs#L114 and according to the docs 
> This rule does nothing if no configurations are provided.
https://eslint.org/docs/rules/padding-line-between-statements

chore: enforce newline before return and after variable declarations

---

renovate.json5

As discussed on slack we should enable lockfile maintenance to catch errors with the latest versions of transitive dependencies.

chore: Enable lockfile maintenance

---

src/feature_flags.ts
src/runtimes/go/index.ts
src/runtimes/node/bundlers/index.ts
tests/main.js

This cleans up 3 feature flags that are already resolved and always on.

refactor: remove feature flag buildGoSource and zisi_detect_esm

---

src/runtimes/node/utils/detect_native_module.ts

Fixes netlify/cli#4612
Add more defensive code so that invalid `files` properties don't make everything explode. See https://github.com/math-utils/hamming-distance/pull/4

fix: handle invalid `files` entry in package.json

---

src/runtimes/go/builder.ts

I noticed that we build for whatever architecture the current host has. Which when for example building locally on M1 MacBook probably creates Linux/arm64 binary which would be wrong, but even if not I feel saver by defining it explicitly.
Ref: https://github.com/netlify/pillar-runtime/issues/231

fix: always build for amd64 when building go functions

---

README.md
src/runtimes/node/bundlers/esbuild/bundler_target.ts
src/runtimes/node/utils/node_version.ts
tests/unit/runtimes/node/utils/node_version.js

As commented by @Skn0tt, we are updating the default nodejs runtime to version 16 but was missing here. The version will be updated on Monday, so we can release it after that. Let me know if I am doing something wrong as it is my first PR here 😄 
---

feat: update default nodejs version to 16

---

src/utils/fs.ts
tests/main.js

For https://github.com/netlify/pod-compute/issues/108
Throws underlying errors if the error is not a FileNotFound Error.

fix: add more error info on missing functions folders

---

src/runtimes/node/bundlers/esbuild/bundler_target.ts
src/runtimes/node/utils/node_version.ts

I noticed this problem while working on another PR that we are missing node 16 in the types. 
I also added more strictness to the types in esbuild that handle the node version.

fix: add node 16 to valid types and be more strict about version in esbuild types

---

.eslintrc.cjs
src/feature_flags.ts
src/runtimes/node/bundlers/esbuild/bundler.ts
src/runtimes/node/bundlers/esbuild/bundler_target.ts
src/runtimes/node/bundlers/esbuild/index.ts
src/runtimes/node/bundlers/index.ts
src/runtimes/node/bundlers/nft/es_modules.ts
src/runtimes/node/bundlers/zisi/src_files.ts
src/runtimes/node/index.ts
src/runtimes/node/parser/index.ts
src/runtimes/node/utils/entry_file.ts
src/runtimes/node/utils/module_format.ts
src/runtimes/node/utils/zip.ts
tests/fixtures/node-mjs-extension/func1.mjs
tests/fixtures/node-mjs-extension/func2/func2.mjs
tests/fixtures/node-mjs-extension/func3/index.mjs
tests/fixtures/node-mjs-extension/node_modules/some-module/index.js
tests/fixtures/node-mjs-extension/node_modules/some-module/package.json
tests/main.js

Currently, ESM functions are transpiled down to CommonJS. With this PR, we'll output pure ESM functions when:
- The input function file has the `.mjs` extension, and
- The `zisi_pure_esm_mjs` feature flag is on
Part of https://github.com/netlify/zip-it-and-ship-it/issues/750.

feat!: output pure ESM for `.mjs` files

---

src/config.ts
src/feature_flags.ts
src/zip.ts
tests/main.js

Adds a `nodeModuleFormat` configuration property. When set to `esm`, it produces the same effect as enabling the `zisi_pure_esm_mjs` feature flag enabled in https://github.com/netlify/zip-it-and-ship-it/pull/1198.

feat: add `nodeModuleFormat` configuration property

---

src/main.ts

To migrate @netlify/build to typescript (part of https://github.com/netlify/build/issues/4472) and make it transpile we need this interface to be exported as it is the return type of a used function
```typescript
const getListedFunction = function ({
runtime,
name,
mainFile,
extension,
config,
inSourceConfig,
}: AugmentedFunctionSource): ListedFunction {
return { name, mainFile, runtime: runtime.name, extension, schedule: inSourceConfig?.schedule ?? config.schedule }
}
```
This changes fixes following error in netlify build:
---
a typo or something that\`s on fire 🔥 (e.g. incident related), you …

fix: emit declaration for ListedFunction for upstream usage in @netlify/build

---

benchmarks/helpers/main.js

chore: fix calculation of average in benchmark

---

.eslintrc.cjs
src/feature_flags.ts
src/runtimes/node/bundlers/esbuild/bundler.ts
tests/fixtures/node-require-in-esm/functions/func1.mjs
tests/fixtures/node-require-in-esm/include.cjs
tests/main.test.ts

This adds a banner to esbuild if the output format is set to ESM. This banner makes require() calls work again. 
This can happen when ESM modules import CJS modules which use `require`.
---

fix: make esbuild work with ESM and require calls

---

package-lock.json
package.json
src/feature_flags.ts
src/main.ts
src/runtimes/detect_runtime.ts
src/runtimes/go/index.ts
src/runtimes/index.ts
src/runtimes/node/bundlers/esbuild/plugin_dynamic_imports.ts
src/runtimes/node/bundlers/esbuild/plugin_native_modules.ts
src/runtimes/node/bundlers/esbuild/src_files.ts
src/runtimes/node/bundlers/nft/es_modules.ts
src/runtimes/node/bundlers/nft/index.ts
src/runtimes/node/bundlers/types.ts
src/runtimes/node/finder.ts
src/runtimes/node/index.ts
src/runtimes/node/parser/index.ts
src/runtimes/node/utils/package_json.ts
src/runtimes/node/utils/zip.ts
src/runtimes/runtime.ts
src/runtimes/rust/builder.ts
src/runtimes/rust/index.ts
src/utils/cache.ts
src/utils/fs.ts
src/zip.ts
tests/unit/runtimes/node/utils/package_json.test.ts

Based on #1243 
Ref: https://github.com/netlify/pod-compute/issues/252
There is also another PR that I created in NFT, as NFT does not correctly cache, which will bring another small performance boost. vercel/nft#320
---

feat: improve performance by reworking caching and supply cache to NFT

---

src/runtimes/node/finder.ts
tests/helpers/main.ts
tests/helpers/test_many.ts

I was investigating why the tests fail sometimes. The tests ensure that when multiple files for the same function exist we always use the same order in how we detect them.
My first thought was it has to do with async stuff in the tests, just to figure out during my perf change I did change `locate-path` to not preserve order, which triggers this flaky behavior.
This reverts this change, plus some additional fixes for the tests, I run into on the way.
---
**A picture of a cute animal (not …

fix: correctly detect conflicting function names consistently

---

package-lock.json
package.json
tests/helpers/main.ts

Sometimes the tests in zisi fail on windows, this happens because the unzip in the tests is running in parallel for all functions. As they all extract to the same directory, permission errors happen when two functions contain the same files, which usually is [the package.json](https://github.com/netlify/zip-it-and-ship-it/blob/main/tests/fixtures/package.json) file.
Also added `@types/tmp`. We are not using tmp directly, but `tmp-promise` uses types from `@types/tmp`
---
**A picture of a cute …

chore: unzip in tests in series and add missing types for tmp

---

.eslintrc.cjs
src/feature_flags.ts
src/runtimes/node/bundlers/esbuild/bundler.ts
tests/fixtures/node-require-in-esm/functions/func1.mjs
tests/fixtures/node-require-in-esm/include.cjs
tests/main.js

fix: (backport) make esbuild work with ESM and require calls (#1257)

---

.eslintrc.cjs
src/feature_flags.ts
src/runtimes/node/bundlers/esbuild/bundler.ts
src/runtimes/node/bundlers/esbuild/index.ts
src/runtimes/node/utils/entry_file.ts
src/runtimes/node/utils/module_format.ts
src/runtimes/node/utils/zip.ts
tests/fixtures/node-js-extension/func1.js
tests/fixtures/node-js-extension/func2/func2.js
tests/fixtures/node-js-extension/func3/index.js
tests/main.test.ts

Fixes https://github.com/netlify/pod-compute/issues/149
This is behind a FF.
With FF enabled:
* esbuild outputs the bundle with cjs extension
* entry-file will be generated with `cjs` extension
Independent of FF we now check for file collisions with all possible entry-files `js, cjs, mjs` and not only with `js`. This is right now not as important as `js` takes precedence over `mjs and cjs` in AWS lambda, but once the FF is on this is critical as we generate the entry file with `cjs` extension but a user-non-main-file could be `func-name.js` and AWS would actually pick this one up instead of our entry-file.
Once we move to having a unique entry file like `__netlifyHandler.(c|m)js` we can clean this all up a lot.
For which functions will there be a hash change (with ff on):
- All functions …

feat: output cjs extension for bundles and entry-files

---

README.md
src/main.ts
src/runtimes/index.ts
tests/fixtures/json-config/.netlify/functions-internal/simple.js
tests/fixtures/json-config/.netlify/functions-internal/simple.json
tests/list_function.test.ts
tests/list_functions.test.ts
tests/list_functions_files.test.ts

Because we want to be able to show the display name in the cli when running `netlify dev` we need to return the displayname from listFunction, listFunctions and listFunctionsFiles.
Connected issue: https://github.com/netlify/pod-compute/issues/373
---

feat: return displayName with json config from listFunction, listFunctions and listFunctionsFiles

---

.github/workflows/pre-release.yml

See https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/ for context.

fix: migrate to Github Action's output files

---

README.md
src/config.ts
src/manifest.ts
src/runtimes/node/bundlers/esbuild/bundler_target.ts
src/runtimes/node/index.ts
src/runtimes/node/utils/node_runtime.ts
src/runtimes/node/utils/node_version.ts
src/runtimes/runtime.ts
tests/__snapshots__/main.test.ts.snap
tests/esbuild.test.ts
tests/main.test.ts
tests/unit/runtimes/node/utils/node_runtime.test.ts
tests/unit/runtimes/node/utils/node_version.test.ts
vitest.config.ts

The option `nodeVersion` now works differently and allows different styles of how the Node.js version is specified.
If it cannot be coerced to a Node.js version, the `undefined` is added to the manifest, leaving the choice of runtime to origin. We could also change this to have zisi add the default to the manifest, but I didn't do it because I feel its nicer to have the default version only in one place.
How it is supposed to work is that `@netlify/build` sets `nodeVersion` to `AWS_LAMBDA_JS_VERSION || buildUserNodeVersion` and based on this input we set a new field `runtimeVersion` in the manifest, or not if it is not a valid runtime version.
open-api reads the manifest and sends `runtimeVersion || runtime`.  In the origin we then detect if it is a runtime shortcut 'js' or a full runtime …

feat: add new runtimeVersion to manifest

---

.github/workflows/integration-tests.yml

Since https://github.com/netlify/next-runtime/pull/2061 was merged the tests here did not work anymore. This PR makes them work again. I simply copied the relevant changes from the next-runtime repo.
I also replaced `KeisukeYamashita/create-comment` with a different action that is maintained.

chore: fix e2e tests

---

.eslintrc.cjs
src/runtimes/node/bundlers/nft/es_modules.ts
src/runtimes/node/utils/entry_file.ts
tests/fixtures/v2-api/package.json
tests/list_functions_files.test.ts

Refs https://github.com/netlify/pod-compute/issues/475
---

fix: do not transpile ESM for v2 functions

---

.github/workflows/integration-tests.yml

cli has no shrinkwrap anymore in the repository.
recording disabled as the key is not set anyway
```
Warning: It looks like you are trying to record this run from a forked PR.
The Record Key is missing. Your CI provider is likely not passing private environment variables to builds from forks.
These results will not be recorded.
This error will not affect or change the exit code.
```

chore: fix integration test caching and remove recording

---

src/zip.ts

This log line shows a large payload for every single function that is bundled. Rather than logging everything by default, let's start with what we know we need and expand from there, to avoid unnecessarily large log volumes.

feat: remove system log for all functions

---

src/runtimes/node/utils/zip.ts
tests/v2api.test.ts

We did not write the bootstrap when the archiveFormat was not zip.
---

fix: write bootstrap also when archive format is not zip

---

src/runtimes/node/index.ts
src/runtimes/node/utils/node_runtime.ts
tests/unit/runtimes/node/utils/node_runtime.test.ts
tests/v2api.test.ts

Currently when a site is using node 16, zisi will set the runtime to `nodejs16.x` even though a v2 function is used. 
This change ensures that we always set at least Node.js 18 for the v2 functions.

fix: select at least Node.js 18 when v2 function detected

---

src/runtimes/node/bundlers/index.ts
src/runtimes/node/bundlers/nft/es_modules.ts
src/runtimes/node/bundlers/nft/index.ts
src/runtimes/node/bundlers/nft/transpile.ts
tests/fixtures/node-typescript-directory-1/function/function.ts
tests/fixtures/node-typescript-directory-2/function/index.ts
tests/fixtures/node-typescript-with-imports/function.ts
tests/fixtures/node-typescript/function.ts
tests/main.test.ts

Currently, TypeScript files are only supported when the bundler is set to esbuild. This PR adds support for TypeScript when using NFT as the bundler.
With that, we also change the upcoming functions API v2 to use NFT by default, instead of esbuild (https://github.com/netlify/zip-it-and-ship-it/pull/1515/commits/2779f306a52033b85e0c5873d592c18e119f3f55).

feat: add support for TypeScript to NFT

---

src/runtimes/node/bundlers/esbuild/bundler.ts
src/runtimes/node/bundlers/esbuild/plugin_dynamic_imports.ts
tests/main.test.ts

As of version 0.19.0, [esbuild can now process some dynamic imports](https://esbuild.github.io/api/#glob), albeit just a subset of the expressions our custom plugin can process. I'd like to understand how many of the expressions people are using in the wild would be supported natively by esbuild, with the view of decommissioning our fork entirely.
With https://github.com/netlify/zip-it-and-ship-it/pull/1445, we started logging any instances where the dynamic imports plugin from our esbuild fork was used to process a dynamic import expression, but we're logging the paths that will be included in the bundle, which is not the most useful piece of informaiton.
This PR changes that so we log the actual dynamic import expression that was used. We can then compare those against the list of …

feat: log dynamic import expressions

---

package-lock.json
package.json

Updates @netlify/esbuild to an updated version of our fork, where something in the installation script was fixed. Because the new version has the same semver version, Renovate won't pick this up - that's why you see me opening this PR manually.

fix: update esbuild to 0.14.39-1

---

src/runtimes/node/in_source_config/index.ts
src/utils/routes.ts
tests/fixtures-esm/v2-api-with-path/with-literal.mjs
tests/unit/runtimes/node/in_source_config.test.ts
tests/v2api.test.ts

Follow-up to https://github.com/netlify/zip-it-and-ship-it/pull/1539 - I forgot to write `methods` into the manifest file!
This PR fixes that.
---

fix: write `methods` into manifest.json

---

src/runtimes/node/bundlers/esbuild/bundler.ts
tests/main.test.ts

Follow-up to #1546. The warning triggered on unnegated patterns, which was incorrect. This PR fixes that.
---

fix: don't warn on unnegated patterns

---

src/feature_flags.ts
src/main.ts
src/runtimes/node/in_source_config/index.ts
src/runtimes/node/index.ts
tests/list_function.test.ts
tests/list_functions.test.ts
tests/unit/runtimes/node/in_source_config.test.ts
tests/v2api.test.ts
tests/zip_function.test.ts

This flag has been rolled out for a while now, without any problems. Let's remove it, so the functionality becomes available in the CLI as well.
Part of https://github.com/netlify/pod-dev-foundations/issues/578.

fix: remove zisi_functions_api_v2 flag

---

src/feature_flags.ts
src/manifest.ts
src/zip.ts

The flag has been rolled out fully for a while, let's remove it.

fix: remove functions_inherit_build_nodejs_version flag

---

src/function.ts
src/runtimes/node/index.ts
tests/fixtures/background/func1-background.js
tests/fixtures/background/func2-background/func2-background.js
tests/fixtures/background/func3-background/index.js
tests/main.test.ts

To support background functions with custom paths, we need to explicitly set `invocationMode: "background"` in the manifest.
Part of https://github.com/netlify/pod-dev-foundations/issues/578.

feat: set `invocationMode` in background functions

---

src/runtimes/node/bundlers/esbuild/bundler.ts
tests/fixtures/import-meta-warning/function.ts
tests/main.test.ts

Replaces a warning text emitted by esbuild with something more actionable.
---

fix: make empty-import-meta warning more actionable

---

package-lock.json
package.json
src/runtimes/node/utils/zip.ts
tests/main.test.ts

Closes https://github.com/netlify/pillar-support/issues/733
If a file was identified by NFT as needing to be included, plus the same file was listet in `included_files`, we are currently calling `zipJsFile` two times for that. This means the file will be zipped twice, redudantly.
This PR adds a repro + fix for that, so we deduplicate files before including them in the zip.
---

fix: dont duplicate zip files

---

src/runtimes/node/bundlers/nft/index.ts
src/runtimes/node/utils/tsconfig.ts

Currently we're only looking at `tsconfig.json` to infer the module type. We need to also look at `package.json` as a fallback.

fix: infer TS module format from `package.json`

---

.github/workflows/integration-tests.yml

The Next runtime now uses Deno as part of its build process, so we need it in our integration tests.

chore: add Deno to integration CI

---

src/runtimes/node/in_source_config/index.ts
src/runtimes/node/parser/exports.ts
src/utils/routes.ts
tests/unit/runtimes/node/in_source_config.test.ts

Allow an array of strings in the `path` in-source configuration property of V2 functions.
The types [already allow this](https://github.com/netlify/functions/blob/3270f5f7823aef8f27e62ab39322514481b7b171/src/function/v2.ts#L10), as well as the rest of the infrastructure.

feat: support multiple paths in V2 functions

---

src/runtimes/node/bundlers/esbuild/bundler.ts
src/runtimes/node/bundlers/index.ts
src/runtimes/node/bundlers/nft/index.ts
src/runtimes/node/bundlers/nft/transpile.ts
src/runtimes/node/index.ts
src/runtimes/node/utils/esm_cjs_compat.ts
src/runtimes/runtime.ts
tests/fixtures-esm/v2-api-esm-mixed-modules/function.ts
tests/fixtures-esm/v2-api-esm-mixed-modules/lib/helper6.js
tests/v2api.test.ts
tests/zip_function.test.ts

This PR has 3 small changes made separately in the following commits:
- https://github.com/netlify/zip-it-and-ship-it/commit/c52807a4a04e329313bbd83f3bb9971fc29d3274 + https://github.com/netlify/zip-it-and-ship-it/pull/1589/commits/802e351c15756436af42a4fc67a4d62f797a68c1: A new `outputModuleFormat` is added to the function objects returned by zip-it-and-ship-it, containing the module format that the function must run as (`cjs` or `esm`)
- https://github.com/netlify/zip-it-and-ship-it/commit/d1b747c3678245a86e0f4855254faef32fb31e24: The `inputs` array in the returned function objects contains the list of paths that acted as inputs to the output function. This is used by the CLI to know which files it needs to watch and associate with each function. Since …

feat: improvements to V2 functions

---

src/runtimes/node/bundlers/nft/bundler.ts
src/runtimes/node/bundlers/nft/index.ts
src/runtimes/node/bundlers/nft/transformer.ts
src/runtimes/node/bundlers/nft/transpile.ts
tests/fixtures-esm/v2-api-cjs-modules/function-js.js
tests/fixtures-esm/v2-api-cjs-modules/function-ts.ts
tests/fixtures-esm/v2-api-esm-mixed-modules/function-js.js
tests/fixtures-esm/v2-api-esm-mixed-modules/function-ts.ts
tests/v2api.test.ts

I realised that we were only transforming V2 functions (i.e. running them through esbuild) when the extension was a TypeScript extension. But we should also do it for JavaScript functions, since bundling local imports is essential to ensure imports between ESM and CJS work as expected.
I ended up renaming the "TS transformer" to a generic transformer, and I moved it into its own file.

feat: always transform V2 functions

---

src/runtimes/node/in_source_config/index.ts
src/runtimes/node/in_source_config/properties/schedule.ts
src/runtimes/node/parser/bindings.ts
src/runtimes/node/parser/exports.ts
tests/unit/runtimes/node/in_source_config.test.ts

Fixes https://github.com/netlify/pod-dev-foundations/issues/599
---

feat: detect literal export as default as a v2 API

---

src/runtimes/go/index.ts

We were only emitting `runtimeVersion: "provided.al2"` when `zipGo` is enabled. In Buildbot deploys, this is disabled, so we weren't emitting `provided.al2` properly! This PR fixes that.
I also noticed we weren't emitting `generator` and `runtimeVersion` when `zipGo` is enabled. I don't think that's intended, so I changed it as well.

fix: output `provided.al2` also when zipGo is disabled

---

src/runtimes/node/utils/zip.ts
tests/main.test.ts

Fixes an issue where on directory mode there was always a `src` folder (which breaks nextjs) and in zip mode there was no `src` folder. Now it uses the same deterministic for creating a src folder in both implementations. Just copied it over for now :)
Currently blocking the next runtime tests
---

fix: fixes an issue where createDirectory created a different structure than createZip

---

src/runtimes/node/utils/zip.ts
tests/fixtures/pnpm-esm-v2/netlify/functions/test.ts
tests/fixtures/pnpm-esm-v2/node_modules/.modules.yaml
tests/fixtures/pnpm-esm-v2/node_modules/.pnpm/filename-reserved-regex@3.0.0/node_modules/filename-reserved-regex/index.js
tests/fixtures/pnpm-esm-v2/node_modules/.pnpm/filename-reserved-regex@3.0.0/node_modules/filename-reserved-regex/license
tests/fixtures/pnpm-esm-v2/node_modules/.pnpm/filename-reserved-regex@3.0.0/node_modules/filename-reserved-regex/package.json
tests/fixtures/pnpm-esm-v2/node_modules/.pnpm/filename-reserved-regex@3.0.0/node_modules/filename-reserved-regex/readme.md
tests/fixtures/pnpm-esm-v2/node_modules/.pnpm/filenamify@6.0.0/node_modules/filename-reserved-regex
tests/fixtures/pnpm-esm-v2/node_modules/.pnpm/filenamify@6.0.0/node_modules/filenamify/filenamify-path.d.ts
tests/fixtures/pnpm-esm-v2/node_modules/.pnpm/filenamify@6.0.0/node_modules/filenamify/filenamify-path.js
tests/fixtures/pnpm-esm-v2/node_modules/.pnpm/filenamify@6.0.0/node_modules/filenamify/filenamify.d.ts
tests/fixtures/pnpm-esm-v2/node_modules/.pnpm/filenamify@6.0.0/node_modules/filenamify/filenamify.js
tests/fixtures/pnpm-esm-v2/node_modules/.pnpm/filenamify@6.0.0/node_modules/filenamify/index.d.ts
tests/fixtures/pnpm-esm-v2/node_modules/.pnpm/filenamify@6.0.0/node_modules/filenamify/index.js
tests/fixtures/pnpm-esm-v2/node_modules/.pnpm/filenamify@6.0.0/node_modules/filenamify/license
tests/fixtures/pnpm-esm-v2/node_modules/.pnpm/filenamify@6.0.0/node_modules/filenamify/package.json
tests/fixtures/pnpm-esm-v2/node_modules/.pnpm/filenamify@6.0.0/node_modules/filenamify/readme.md
tests/fixtures/pnpm-esm-v2/node_modules/.pnpm/lock.yaml
tests/fixtures/pnpm-esm-v2/node_modules/.pnpm/node_modules/filename-reserved-regex
tests/fixtures/pnpm-esm-v2/node_modules/filenamify
tests/fixtures/pnpm-esm-v2/package.json
tests/fixtures/pnpm-esm-v2/pnpm-lock.yaml
tests/v2api.test.ts

When creating a bundle into a directory, we need to respect symlinks and not just copy them as files.
Fixes https://github.com/netlify/cli/issues/6106

fix: handle symlinks when creating directory

---

src/runtimes/node/in_source_config/index.ts
src/utils/routes.ts
tests/unit/runtimes/node/in_source_config.test.ts

Adds a `preferStatic` property to the in-source configuration that lets developers configure the file shadowing behaviour on a per-function basis.
Part of https://linear.app/netlify/issue/COM-32/functions-v2-inline-config-does-not-respect-cdn-shadowing.

feat: add `preferStatic` to ISC

---

src/runtimes/node/parser/exports.ts
tests/unit/runtimes/node/in_source_config.test.ts

Some Frameworks, like Remix, use ESBuild under the hood and don't allow changing its settings. In the case of Remix, it performs some sort of minification on the server code that transforms boolean literals into `!0` and `!1`. This PR teaches ZISI how to interpret those.

fix: parse minified boolean

---

.github/workflows/integration-tests.yml

With https://github.com/netlify/cli/commit/5eb2133a277191c68e6d2129f0ebe6d5d85a9402, the CLI changed the file format of `run.mjs` to `run.js`. Gotta move our test along!

fix: integration test needs to use run.js instead of run.mjs

---

src/manifest.ts
src/priority.ts
src/runtimes/node/index.ts
src/runtimes/runtime.ts
tests/main.test.ts

Adds a `priority` field to the functions manifest file based on whether it was generated by an integration or authored by a user.
Part of COM-327.

feat: add `priority` field to manifest

---

src/runtimes/node/utils/zip.ts
tests/fixtures-esm/symlinked-bin/function.ts
tests/fixtures-esm/symlinked-bin/subproject/node_modules/.bin/cli.js
tests/fixtures-esm/symlinked-bin/subproject/node_modules/tool/cli.js
tests/symlinked_included_files.test.ts

Fixes https://github.com/netlify/cli/issues/6106, https://linear.app/netlify/issue/COM-351/esm-dependencies-in-v2-functions-in-pnpm-repo-cause-crash-in-dev.
For `includedFiles`, we're recreating symlinks, sometimes in nested paths. Sometimes this breaks because the target directory doesn't exist. This PR fixes that by ensuring that a symlinks containing directory is created before the symlink itself is created.
---
**A picture of a cute animal (not …

fix: create symlink parent directory before creating symlink itself

---

src/main.ts
src/runtimes/node/in_source_config/index.ts
src/runtimes/node/index.ts
tests/unit/runtimes/node/in_source_config.test.ts
tests/v2api.test.ts
tests/zip_function.test.ts

Cleaning up a system log line that I don't think is useful anymore, since the V2 detection mechanism has been proven to work and we have other ways of identifying the runtime version of a given function.

feat: stop logging V2 function detection
